apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-configmap
data:
  MICRO_CLIENT_ID: {{.Values.env.MICRO_CLIENT_ID }}
  MICRO_CLIENT_SECRET: {{.Values.env.MICRO_CLIENT_SECRET }}
  SQLALCHEMY_DATABASE_URI: {{.Values.env.SQLALCHEMY_DATABASE_URI }}
  DEBUG: "{{.Values.env.DEBUG }}"
  REDIRECT_URL: {{.Values.env.REDIRECT_URL }}