apiVersion: v1
kind: Service
metadata:
  name: myportal-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5000
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: myportal