moodleUsername: "${app_username}"
moodlePassword: "${app_password}"
allowEmptyPassword: false
global:
  storageClass: "efs-sc"
mariadb:
  enabled: false
volumePermissions:
  enabled: false
persistence:
  enabled: true
  accessMode: ReadWriteMany
  existingClaim: efs-claim 
image:
  debug: true
externalDatabase:
  type: auroramysql
  host: "${db_endpoint}"
  user: "${db_username}"
  password: "${db_password}"
  database: "${db_name}"

image:
  registry: docker.io
  repository: bitnami/moodle
  pullPolicy: IfNotPresent
  debug: true

service:
  type: ClusterIP
  # annotations: 
  #   service.beta.kubernetes.io/aws-load-balancer-type: alb
resourcePreset: large
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 4
  targetCPU: 30
  targetMemory: 80

ingress:
  enabled: true
  hostname: "school.pikaamail.com"
  tls: true
  ingressClassName: alb
  path: /*
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: ${certificate_arn}
  extraRules:
    - host: "myportal.pikaamail.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: myportal-service
              port:
                number: 443
startupProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 200
  successThreshold: 1